### PR TITLE
#[184651058] [Setup docker for backend application]

### PR DESCRIPTION
**Pull request by Pacific911**
### What does this PR do?
Sets Up the docker configuration to run to another machine or another environment

### Description of Task to be completed?
- Create Docker file that consists of the commands to allow docker to run
- A full directory with all folders that a developer might need
- Install the docker app and enable the virtualization in the BIOS settings

#### How should this be manually tested?
-Enable the virtualization in BIOS settings and open the docker hub to run the application

### Any background context you want to provide?
- I downloaded the docker app and tested the run into the docker hub

#### What are the relevant pivotal tracker/Trello stories?
#184651058

### CODE REVIEW

**Comment by munezerobagira** [comment]
Work on this feedback and your PR will be merged.

**Comment by munezerobagira** [comment]
- Please check your PR title
- and commit message
- and remember to assign the PR to yourself

**Comment by Pacific911** [comment]
changes requested done

**Comment by munezerobagira** [comment]
We have conflicts, and there are some comments which have not been addressed

**Comment by Pacific911** [comment]
requested changes solved

**Pull request closed without merging**
