### PR TITLE
#184651056  Configure Swagger Documentation

### PR DESCRIPTION
**Pull request by princoo**
- swagger docs congiguration

[Delivers #184651056]

### What does this PR do?
Creates a base configuration for swagger documentation
### Description of Task to be completed?
- implemented swagger doc
- able to test APIs using swagger UI
### How should this be manually tested
- connect to the server: **npm run start**
- in the browser use: **http://site_url/myapi**
### Any background context you want to provide?
- this will make it possible to make documentation using swagger annotations

### CODE REVIEW

**Comment by munezerobagira** [comment]
can you resolve the conflict

**Comment by princoo** [comment]
conflicts resolved

**Review by munezerobagira — APPROVED** [review]

**Review by Edcreation — APPROVED** [review]
***Swagger docs nicely configured.***

**Review by Kress2000 — APPROVED** [review]

**Review by Pacific911 — APPROVED** [review]
LGTM

**Pull request merged**
